services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - /srv/docker/appdata/jellyfin/config:/config
      - /srv/docker/appdata/jellyfin/cache:/cache
      - /srv/media:/media
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    ports:
      - "8989:8989"
    volumes:
      - /srv/docker/appdata/sonarr/config:/config
      - /srv/media/shows:/shows
      - /srv/torrents/complete:/downloads
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    ports:
      - "7878:7878"
    volumes:
      - /srv/docker/appdata/radarr/config:/config
      - /srv/media/movies:/movies
      - /srv/torrents/complete:/downloads
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    ports:
      - "9696:9696"
    volumes:
      - /srv/docker/appdata/prowlarr/config:/config
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    ports:
      - "8080:8080"
      - "6881:6881"
    volumes:
      - /srv/docker/appdata/qbittorrent/config:/config
      - /srv/torrents:/downloads
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    ports:
      - "6767:6767"
    volumes:
      - /srv/docker/appdata/bazarr/config:/config
      - /srv/media/movies:/movies
      - /srv/media/shows:/shows
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    ports:
      - "5055:5055"
    volumes:
      - /srv/docker/appdata/overseerr/config:/app/config
    restart: unless-stopped
